version: 2
jobs:
  build:
    working_directory: /workspace
    docker:
    - image: node:7.9
    environment:
      CHROME_BIN: /usr/bin/chromium
      DOCKER_VERSION: 17.04.0-ce

    steps:

    - run:
        name: update yarn
        command: |
          # remove default yarn
          rm -rf $(dirname $(which yarn))/yarn*
          # download latest
          rm -rf ~/.yarn
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.4
          echo 'export PATH="${PATH}:${HOME}/.yarn/bin"' >> $BASH_ENV

    - run:
        name: Install Chromium and Xvfb
        command: apt-get update -qq && apt-get install -qq -y chromium Xvfb > /dev/null

    - setup_remote_docker

    - checkout

    - restore_cache:
        key: atlasmap-ui-{{ checksum "package.json" }}

    - run:
        name: Install Dependencies
        command: yarn install --verbose --no-progress

    - save_cache:
        key: atlasmap-ui-{{ checksum "package.json" }}
        paths:
        - ~/.yarn
        - ~/.cache/yarn

    - run:
        name: Run AOT compile
        command: |
          yarn aot:build

    - run:
        name: Run unit tests
        command: |
          rm -Rf ./coverage ./junit
          mkdir ./coverage ./junit
          ./karma-xvfb.sh

    - store_test_results:
        path: ./junit

    - run:
        name: Lint
        command: npm run lint

    - store_artifacts:
        path: ./dist
    - store_artifacts:
        path: ./coverage
    - store_artifacts:
        path: ./junit

    - deploy:
        command: |
          if [ "${CIRCLE_PROJECT_USERNAME}" != "atlasmap" ]; then
            exit 0
          fi

          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            TAG=`npm run version|sed '$!d'`.`date '+%Y%m%d%H%M%S'`
            cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage
          elif [[ "${CIRCLE_TAG}" =~ ^[0-9]+(\.[0-9]+){2} ]]; then
            TAG="${CIRCLE_TAG}"
          else
            exit 0
          fi

          echo "Publishing atlasmap.data.mapper ${TAG}..."

          git config --global user.name "AtlasMap CI"
          git config --global user.email "tm.igarashi+atlasmapci@gmail.com"
          npm version ${TAG}

          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          npm publish

          # git push --follow-tags
